# Pandas

In [1]:
""""
pip install pandas   ------> to install pandas in vs code
import pandas as pd  (importing pandas and giving "pd" as alias name)

Panda is a python library used for manipulation and analysis.
It has 2 data structure:-
1)Series
2)Data frame

"""

'"\npip install pandas   ------> to install pandas in vs code\nimport pandas as pd  (importing pandas and giving "pd" as alias name)\n\nPanda is a python library used for manipulation and analysis.\nIt has 2 data structure:-\n1)Series\n2)Data frame\n\n'

In [2]:
import pandas as pd
import numpy as np

### 1)Series

In [3]:
# creating a series

ser = pd.Series() 
print("Pandas Series: ", ser,'\n') 

data = np.array(['g', 'e', 'e', 'k', 's']) 
  
ser = pd.Series(data) 
print("Pandas Series:\n", ser)

Pandas Series:  Series([], dtype: object)

Pandas Series:
 0    g
1    e
2    e
3    k
4    s
dtype: object

In [4]:
s1=pd.Series([10,20,30,40,'hello',[1,2,4]])
print(s1)
print("***************************************************************************************************")
print(type(s1))
print("***************************************************************************************************")

s1[4]='hi'
s2=pd.Series([1,2,3,4,'world',[9]])
print(s1+s2)
print("***************************************************************************************************")
print(s1)
print("***************************************************************************************************")
print(s2)
print("***************************************************************************************************")
print(s1[4])

0           10
1           20
2           30
3           40
4        hello
5    [1, 2, 4]
dtype: object
***************************************************************************************************
<class 'pandas.core.series.Series'>
***************************************************************************************************
0              11
1              22
2              33
3              44
4         hiworld
5    [1, 2, 4, 9]
dtype: object
***************************************************************************************************
0           10
1           20
2           30
3           40
4           hi
5    [1, 2, 4]
dtype: object
***************************************************************************************************
0        1
1        2
2        3
3        4
4    world
5      [9]
dtype: object
***************************************************************************************************
hi

In [5]:
s3=pd.Series([1,2,3,4,5,6,7,8,9],name="marks")
print(s3)
s4=s3[3:8:2]
print(s4)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
Name: marks, dtype: int64
3    4
5    6
7    8
Name: marks, dtype: int64

### 2)Data frame

In [6]:
df=pd.DataFrame({"Name":['Yami','Deepa',],
                 "Marks":[69,96],
                 "Rollno":[76,129]})

df

    Name  Marks  Rollno
0   Yami     69      76
1  Deepa     96     129

In [7]:
# DATA FRAMES

df1=pd.DataFrame({"Name":['Yami','Deepa','Yamini','Deepika','Deeya'],
                 "Ratings":['1*','1','2*','2','1*'],
                 "Qualification":['MCA','MCA','BCA','BCA','B.Tech']})

df1

      Name Ratings Qualification
0     Yami      1*           MCA
1    Deepa       1           MCA
2   Yamini      2*           BCA
3  Deepika       2           BCA
4    Deeya      1*        B.Tech

In [8]:
"""
pd.read_csv is used to read the file in this we read file that is in same folder

"""
d1=pd.read_csv('flipkart_sales.csv')
d1

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating
0,ORD00001,Educational Book,Books,49069.56,2,98139.12,2024-09-12,Debit Card,3.5
1,ORD00002,Jeans,Clothing,12755.85,4,51023.40,2024-12-18,UPI,3.9
2,ORD00003,Face Cream,Beauty,11092.19,4,44368.76,2024-05-18,Debit Card,4.4
3,ORD00004,Smartwatch,Electronics,32657.81,1,32657.81,2024-11-08,Debit Card,3.2
4,ORD00005,Cookware Set,Home & Kitchen,26590.08,3,79770.24,2024-12-27,UPI,3.1
...,...,...,...,...,...,...,...,...,...
995,ORD00996,Smartphone,Electronics,28995.81,3,86987.43,2025-01-13,COD,5.0
996,ORD00997,Perfume,Beauty,32799.51,2,65599.02,2024-12-18,Wallet,2.4
997,ORD00998,Face Cream,Beauty,40840.80,1,40840.80,2024-07-26,UPI,3.1
998,ORD00999,Cookware Set,Home & Kitchen,34741.79,4,138967.16,2024-10-02,Net Banking,3.2
999,ORD01000,Table Lamp,Home & Kitchen,16698.12,4,66792.48,2024-03-26,Credit Card,1.6

In [9]:
d1['Product Name']           # accesing column

0      Educational Book
1                 Jeans
2            Face Cream
3            Smartwatch
4          Cookware Set
             ...
995          Smartphone
996             Perfume
997          Face Cream
998        Cookware Set
999          Table Lamp
Name: Product Name, Length: 1000, dtype: object

In [10]:
# here we read a file from a link of github
d2=pd.read_csv('https://raw.githubusercontent.com/whoknowayush/DataAnalysis-Dataset/refs/heads/main/Datasets-Practice/hr_data.csv')
d2

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

In [11]:
# its a 2-D and consistsof row& series
# syntax :- pd.DataFrame(dictionaty)

# Creating a dictionary
data1 = {
    "emp_name": ["Rahul", "Priya", "Aman", "Sneha", "Karan", "Meera", "Vikas", "Anita", "Rohit", "Tina"],
    "emp_loc": ["Delhi", "Mumbai", "Bangalore", "Chennai", "Pune", "Hyderabad", "Kolkata", "Jaipur", "Surat", "Noida"],
    "emp_sal": [45000, 52000, 48000, 50000, 47000, 55000, 53000, 46000, 60000, 49000],
    "emp_designation": ["Developer", "Analyst", "Tester", "Manager", "Designer", "HR", "Developer", "Analyst", "Manager", "Tester"],
    "emp_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110]
}

# Creating DataFrame
emp_df = pd.DataFrame(data1)
emp_df

  emp_name    emp_loc  emp_sal emp_designation  emp_id
0    Rahul      Delhi    45000       Developer     101
1    Priya     Mumbai    52000         Analyst     102
2     Aman  Bangalore    48000          Tester     103
3    Sneha    Chennai    50000         Manager     104
4    Karan       Pune    47000        Designer     105
5    Meera  Hyderabad    55000              HR     106
6    Vikas    Kolkata    53000       Developer     107
7    Anita     Jaipur    46000         Analyst     108
8    Rohit      Surat    60000         Manager     109
9     Tina      Noida    49000          Tester     110

In [12]:
data2 = {
    "cust_name": ["Arjun", "Nisha", "Ravi", "Simran", "Kunal",
                  "Meera", "Varun", "Pooja", "Sahil", "Ananya"],
    "phno": [9876543210, 9123456780, 9988776655, 9090909090, 9112233445,
             9001122334, 9898989898, 9223344556, 9332211000, 9887766554],
    "rating": [4.5, 4.0, 3.8, 5.0, 4.2, 4.1, 3.9, 4.7, 4.3, 4.8]
}

cust_df = pd.DataFrame(data2)
cust_df

  cust_name        phno  rating
0     Arjun  9876543210     4.5
1     Nisha  9123456780     4.0
2      Ravi  9988776655     3.8
3    Simran  9090909090     5.0
4     Kunal  9112233445     4.2
5     Meera  9001122334     4.1
6     Varun  9898989898     3.9
7     Pooja  9223344556     4.7
8     Sahil  9332211000     4.3
9    Ananya  9887766554     4.8

In [13]:
d2=pd.read_csv('https://raw.githubusercontent.com/whoknowayush/DataAnalysis-Dataset/refs/heads/main/Datasets-Practice/hr_data.csv')
d2

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

In [14]:
d2.head()                  # gives by default only first 5 rows

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low

In [15]:
d2.head(10)                # gives first n no. of  rows

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
5,1060,2,153,3,0,1,0,sales,low
6,1061,6,247,4,0,1,0,sales,low
7,1576,5,259,5,0,1,0,sales,low
8,1752,5,224,5,0,1,0,sales,low
9,1988,2,142,3,0,1,0,sales,low

In [16]:
d2.tail()                  # gives by default only last 5 rows

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

In [17]:
d2.tail(10)                # gives last n no. of  rows

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
14989,87638,2,159,3,1,1,0,technical,low
14990,87639,5,228,5,1,1,0,support,low
14991,87654,6,257,4,0,1,0,support,low
14992,87656,2,155,3,0,1,0,support,low
14993,87661,6,293,6,0,1,0,support,low
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

In [18]:
d2.describe()              # overall statistic of the numerical data present inside dataset

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years
count,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000
mean,45424.627575,3.803054,201.050337,3.498233,0.144610,0.238083,0.021268
std,25915.900127,1.232592,49.943099,1.460136,0.351719,0.425924,0.144281
min,1003.000000,2.000000,96.000000,2.000000,0.000000,0.000000,0.000000
25%,22872.500000,3.000000,156.000000,3.000000,0.000000,0.000000,0.000000
50%,45448.000000,4.000000,200.000000,3.000000,0.000000,0.000000,0.000000
75%,67480.500000,5.000000,245.000000,4.000000,0.000000,0.000000,0.000000
max,99815.000000,7.000000,310.000000,10.000000,1.000000,1.000000,1.000000

In [19]:
d2.info()                  # provides information of each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   employee_id            14999 non-null  int64
 1   number_project         14999 non-null  int64
 2   average_montly_hours   14999 non-null  int64
 3   time_spend_company     14999 non-null  int64
 4   Work_accident          14999 non-null  int64
 5   left                   14999 non-null  int64
 6   promotion_last_5years  14999 non-null  int64
 7   department             14999 non-null  object
 8   salary                 14999 non-null  object
dtypes: int64(7), object(2)
memory usage: 1.0+ MB

In [20]:
d2.columns                 # gives all columns name

Index(['employee_id', 'number_project', 'average_montly_hours',
       'time_spend_company', 'Work_accident', 'left', 'promotion_last_5years',
       'department', 'salary'],
      dtype='object')

In [21]:
# d1.loc[row_slicing,column_slicing]
d1.loc[1:10,['Order ID','Category']]                          # if multiple row are there wrap it inside squre bracket

    Order ID        Category
1   ORD00002        Clothing
2   ORD00003          Beauty
3   ORD00004     Electronics
4   ORD00005  Home & Kitchen
5   ORD00006  Home & Kitchen
6   ORD00007        Clothing
7   ORD00008  Home & Kitchen
8   ORD00009        Clothing
9   ORD00010     Electronics
10  ORD00011          Beauty

In [22]:
d1.loc[[1,2,5,7,9,13],['Order ID','Category']]                # it is used to retrive row and columns

    Order ID        Category
1   ORD00002        Clothing
2   ORD00003          Beauty
5   ORD00006  Home & Kitchen
7   ORD00008  Home & Kitchen
9   ORD00010     Electronics
13  ORD00014     Electronics

In [23]:
# d1.iloc[row_slicing,column_slicing]                         # it will take row index and column index
d1.iloc[0:15,0:7]

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date
0,ORD00001,Educational Book,Books,49069.56,2,98139.12,2024-09-12
1,ORD00002,Jeans,Clothing,12755.85,4,51023.40,2024-12-18
2,ORD00003,Face Cream,Beauty,11092.19,4,44368.76,2024-05-18
3,ORD00004,Smartwatch,Electronics,32657.81,1,32657.81,2024-11-08
4,ORD00005,Cookware Set,Home & Kitchen,26590.08,3,79770.24,2024-12-27
5,ORD00006,Mixer Grinder,Home & Kitchen,10475.03,2,20950.06,2024-10-22
6,ORD00007,Sneakers,Clothing,38647.72,3,115943.16,2024-07-04
7,ORD00008,Table Lamp,Home & Kitchen,24818.59,3,74455.77,2024-12-27
8,ORD00009,Jacket,Clothing,1987.39,2,3974.78,2025-01-18
9,ORD00010,Tablet,Electronics,26876.51,2,53753.02,2024-03-14
10,ORD00011,Perfume,Beauty,46409.57,5,232047.85,2025-02-08
11,ORD00012,Lipstick,Beauty,48780.78,5,243903.90,2024-04-13
12,ORD00013,Educational Book,Books,6670.82,5,33354.10,2024-02-23
13,ORD00014,Smartphone,Electronics,10826.05,1,10826.05,2024-06-02
14,ORD00015,Comic Book,Books,6839.10,1,6839.10,2024-09-12

In [24]:
d1.iloc[[1,2,4,6],[2,3,5,8]]

         Category  Price (INR)  Total Sales (INR)  Customer Rating
1        Clothing     12755.85           51023.40              3.9
2          Beauty     11092.19           44368.76              4.4
4  Home & Kitchen     26590.08           79770.24              3.1
6        Clothing     38647.72          115943.16              2.0

In [25]:
emp_df['emp_exp'] = 2   # experience=2 years for all employees
emp_df

  emp_name    emp_loc  emp_sal emp_designation  emp_id  emp_exp
0    Rahul      Delhi    45000       Developer     101        2
1    Priya     Mumbai    52000         Analyst     102        2
2     Aman  Bangalore    48000          Tester     103        2
3    Sneha    Chennai    50000         Manager     104        2
4    Karan       Pune    47000        Designer     105        2
5    Meera  Hyderabad    55000              HR     106        2
6    Vikas    Kolkata    53000       Developer     107        2
7    Anita     Jaipur    46000         Analyst     108        2
8    Rohit      Surat    60000         Manager     109        2
9     Tina      Noida    49000          Tester     110        2

In [26]:
emp_df['emp_exp'] = [1, 3, 2, 4, 5, 1, 2, 3, 4, 6]
emp_df

  emp_name    emp_loc  emp_sal emp_designation  emp_id  emp_exp
0    Rahul      Delhi    45000       Developer     101        1
1    Priya     Mumbai    52000         Analyst     102        3
2     Aman  Bangalore    48000          Tester     103        2
3    Sneha    Chennai    50000         Manager     104        4
4    Karan       Pune    47000        Designer     105        5
5    Meera  Hyderabad    55000              HR     106        1
6    Vikas    Kolkata    53000       Developer     107        2
7    Anita     Jaipur    46000         Analyst     108        3
8    Rohit      Surat    60000         Manager     109        4
9     Tina      Noida    49000          Tester     110        6

In [27]:
cust_df['cust_description'] = "Regular Customer"
cust_df

  cust_name        phno  rating  cust_description
0     Arjun  9876543210     4.5  Regular Customer
1     Nisha  9123456780     4.0  Regular Customer
2      Ravi  9988776655     3.8  Regular Customer
3    Simran  9090909090     5.0  Regular Customer
4     Kunal  9112233445     4.2  Regular Customer
5     Meera  9001122334     4.1  Regular Customer
6     Varun  9898989898     3.9  Regular Customer
7     Pooja  9223344556     4.7  Regular Customer
8     Sahil  9332211000     4.3  Regular Customer
9    Ananya  9887766554     4.8  Regular Customer

In [28]:
cust_df['cust_description'] = ["Premium","Regular","New","Returning","VIP","Regular","New","Premium","Regular","VIP"]
cust_df

  cust_name        phno  rating cust_description
0     Arjun  9876543210     4.5          Premium
1     Nisha  9123456780     4.0          Regular
2      Ravi  9988776655     3.8              New
3    Simran  9090909090     5.0        Returning
4     Kunal  9112233445     4.2              VIP
5     Meera  9001122334     4.1          Regular
6     Varun  9898989898     3.9              New
7     Pooja  9223344556     4.7          Premium
8     Sahil  9332211000     4.3          Regular
9    Ananya  9887766554     4.8              VIP

In [29]:
d1=pd.DataFrame({'st_name':['pinkiu','harshit','chintu','karan','chintu'],
                  'st_id':[102,103,104,105,104],
                  'st_age':[16,17,18,15,18],
                  'st_ph':[9668193293,9556867980,9732145869,7788993344,9732145869],
                  'st_marks':[99,98,97,96,95]})
d1

   st_name  st_id  st_age       st_ph  st_marks
0   pinkiu    102      16  9668193293        99
1  harshit    103      17  9556867980        98
2   chintu    104      18  9732145869        97
3    karan    105      15  7788993344        96
4   chintu    104      18  9732145869        95

In [30]:
#change column
# st_ph----> st_phno
# st_mark--->st_score

d1.rename(columns={'st_ph':'st_phno','st_marks':'st_scores'},inplace=True)
d1

   st_name  st_id  st_age     st_phno  st_scores
0   pinkiu    102      16  9668193293         99
1  harshit    103      17  9556867980         98
2   chintu    104      18  9732145869         97
3    karan    105      15  7788993344         96
4   chintu    104      18  9732145869         95

In [31]:
#By default inplace=false which will not change permanently so we have to assign it True
d1.rename(columns={'st_id':'st_rollno','st_age':'age','st_name':'st'},inplace=True)
d1

        st  st_rollno  age     st_phno  st_scores
0   pinkiu        102   16  9668193293         99
1  harshit        103   17  9556867980         98
2   chintu        104   18  9732145869         97
3    karan        105   15  7788993344         96
4   chintu        104   18  9732145869         95

In [32]:
# it will remove the duplicates from the dataframe which are having same column but temporary
d1.drop_duplicates()
d1

        st  st_rollno  age     st_phno  st_scores
0   pinkiu        102   16  9668193293         99
1  harshit        103   17  9556867980         98
2   chintu        104   18  9732145869         97
3    karan        105   15  7788993344         96
4   chintu        104   18  9732145869         95

In [33]:
# but d1.drop_duplicates() will delete duplicate temporaryly to do it permanant we have to write  inplace=True

d1.drop_duplicates(inplace=True) 
d1 

# or we can write
d1=d1.drop_duplicates()
d1

        st  st_rollno  age     st_phno  st_scores
0   pinkiu        102   16  9668193293         99
1  harshit        103   17  9556867980         98
2   chintu        104   18  9732145869         97
3    karan        105   15  7788993344         96
4   chintu        104   18  9732145869         95

In [34]:
# upd_marks1={98:89,96:69,89:96,78:70}              # by using map if it will not find the key it will show NaN value to overcome it we use replace
# d1['st_scores']=d1['st_scores'].map(upd_marks1)
# d1

"""
output

	st	st_rollno	age	st_phno	st_scores
0	pinkiu	102	16	9668193293	NaN
1	harshit	103	17	9556867980	89.0
2	chintu	104	18	9732145869	NaN
3	karan	105	15	7788993344	69.0
4	chintu	104	18	9732145869	NaN


"""

'\noutput\n\n\tst\tst_rollno\tage\tst_phno\tst_scores\n0\tpinkiu\t102\t16\t9668193293\tNaN\n1\tharshit\t103\t17\t9556867980\t89.0\n2\tchintu\t104\t18\t9732145869\tNaN\n3\tkaran\t105\t15\t7788993344\t69.0\n4\tchintu\t104\t18\t9732145869\tNaN\n\n\n'

In [35]:
upd_marks2={98:89,96:69,89:96,78:70}                   # it will not show NaN it will replace
d1['st_scores']=d1['st_scores'].replace(upd_marks2)
d1

        st  st_rollno  age     st_phno  st_scores
0   pinkiu        102   16  9668193293         99
1  harshit        103   17  9556867980         89
2   chintu        104   18  9732145869         97
3    karan        105   15  7788993344         69
4   chintu        104   18  9732145869         95

In [36]:
emp=pd.DataFrame({'emp_name':['Kartik', 'Mohan','Sohan', 'Sahil','Karan','Arjun'],
                  'emp_id':[1234,1235,1236,1237,1238,1239],
                  'emp_role':['SE','SE','ASE','JSE','OA','DS'],
                  'emp_years':[2,2,1,1,4,5]})
emp

  emp_name  emp_id emp_role  emp_years
0   Kartik    1234       SE          2
1    Mohan    1235       SE          2
2    Sohan    1236      ASE          1
3    Sahil    1237      JSE          1
4    Karan    1238       OA          4
5    Arjun    1239       DS          5

In [37]:
emp.rename(columns={'emp_role':'emp_designation','emp_years':'emp_exp'},inplace=True)    # inplace=True means change permanantly
emp

  emp_name  emp_id emp_designation  emp_exp
0   Kartik    1234              SE        2
1    Mohan    1235              SE        2
2    Sohan    1236             ASE        1
3    Sahil    1237             JSE        1
4    Karan    1238              OA        4
5    Arjun    1239              DS        5

In [38]:
emp['emp_exp']=emp['emp_exp'].replace({1:2})
emp

  emp_name  emp_id emp_designation  emp_exp
0   Kartik    1234              SE        2
1    Mohan    1235              SE        2
2    Sohan    1236             ASE        2
3    Sahil    1237             JSE        2
4    Karan    1238              OA        4
5    Arjun    1239              DS        5

In [39]:
emp['emp_designation']=emp['emp_designation'].map({'SE':'SR.SE','ASE':'SE','JSE':'ASE','OA':'OS','DS':'SRDS'})
emp

  emp_name  emp_id emp_designation  emp_exp
0   Kartik    1234           SR.SE        2
1    Mohan    1235           SR.SE        2
2    Sohan    1236              SE        2
3    Sahil    1237             ASE        2
4    Karan    1238              OS        4
5    Arjun    1239            SRDS        5

In [40]:
d3 = pd.read_csv('https://raw.githubusercontent.com/whoknowayush/DataAnalysis-Dataset/main/Datasets-Practice/amazon_fires.csv',encoding='ISO-8859-1')
d3

       ano       mes     estado   numero  encontro
0     1998   Janeiro       Acre  0 Fires  1/1/1998
1     1999   Janeiro       Acre  0 Fires  1/1/1999
2     2000   Janeiro       Acre  0 Fires  1/1/2000
3     2001   Janeiro       Acre  0 Fires  1/1/2001
4     2002   Janeiro       Acre  0 Fires  1/1/2002
...    ...       ...        ...      ...       ...
6449  2012  Dezembro  Tocantins      128  1/1/2012
6450  2013  Dezembro  Tocantins       85  1/1/2013
6451  2014  Dezembro  Tocantins      223  1/1/2014
6452  2015  Dezembro  Tocantins      373  1/1/2015
6453  2016  Dezembro  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

In [41]:
print(d3.info())
d3.rename(columns={'ano':'year','mes':'month','estado':'state','numero':'number_of_fire','encontro':'Date'},inplace=True)
d3

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6454 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ano       6454 non-null   int64
 1   mes       6454 non-null   object
 2   estado    6454 non-null   object
 3   numero    6322 non-null   object
 4   encontro  6454 non-null   object
dtypes: int64(1), object(4)
memory usage: 252.2+ KB
None

      year     month      state number_of_fire      Date
0     1998   Janeiro       Acre        0 Fires  1/1/1998
1     1999   Janeiro       Acre        0 Fires  1/1/1999
2     2000   Janeiro       Acre        0 Fires  1/1/2000
3     2001   Janeiro       Acre        0 Fires  1/1/2001
4     2002   Janeiro       Acre        0 Fires  1/1/2002
...    ...       ...        ...            ...       ...
6449  2012  Dezembro  Tocantins            128  1/1/2012
6450  2013  Dezembro  Tocantins             85  1/1/2013
6451  2014  Dezembro  Tocantins            223  1/1/2014
6452  2015  Dezembro  Tocantins            373  1/1/2015
6453  2016  Dezembro  Tocantins            119  1/1/2016

[6454 rows x 5 columns]

In [42]:
d3.duplicated().sum()

np.int64(30)

In [43]:
d3['month'].value_counts()
d3.drop_duplicates(inplace=True)
d3

      year     month      state number_of_fire      Date
0     1998   Janeiro       Acre        0 Fires  1/1/1998
1     1999   Janeiro       Acre        0 Fires  1/1/1999
2     2000   Janeiro       Acre        0 Fires  1/1/2000
3     2001   Janeiro       Acre        0 Fires  1/1/2001
4     2002   Janeiro       Acre        0 Fires  1/1/2002
...    ...       ...        ...            ...       ...
6449  2012  Dezembro  Tocantins            128  1/1/2012
6450  2013  Dezembro  Tocantins             85  1/1/2013
6451  2014  Dezembro  Tocantins            223  1/1/2014
6452  2015  Dezembro  Tocantins            373  1/1/2015
6453  2016  Dezembro  Tocantins            119  1/1/2016

[6424 rows x 5 columns]

In [44]:
d3['month'] = d3['month'].str.strip().str.lower()
d3

      year     month      state number_of_fire      Date
0     1998   janeiro       Acre        0 Fires  1/1/1998
1     1999   janeiro       Acre        0 Fires  1/1/1999
2     2000   janeiro       Acre        0 Fires  1/1/2000
3     2001   janeiro       Acre        0 Fires  1/1/2001
4     2002   janeiro       Acre        0 Fires  1/1/2002
...    ...       ...        ...            ...       ...
6449  2012  dezembro  Tocantins            128  1/1/2012
6450  2013  dezembro  Tocantins             85  1/1/2013
6451  2014  dezembro  Tocantins            223  1/1/2014
6452  2015  dezembro  Tocantins            373  1/1/2015
6453  2016  dezembro  Tocantins            119  1/1/2016

[6424 rows x 5 columns]

In [45]:
d3['month'].unique()

array(['janeiro', 'fevereiro', 'março', 'abril', 'maio', 'junho', 'julho',
       'agosto', 'setembro', 'outubro', 'novembro', 'dezembro'],
      dtype=object)

In [46]:
# to change or update row value use map function
# inclue all the unique values otherwise it will provide NaN value

month_map = {
    'janeiro': 'January',
    'fevereiro': 'February',
    'março': 'March',
    'abril': 'April',
    'maio': 'May',
    'junho': 'June',
    'julho': 'July',
    'agosto': 'August',
    'setembro': 'September',
    'outubro': 'October',
    'novembro': 'November',
    'dezembro': 'December'
}

d3['month'] = d3['month'].map(month_map)
d3

      year     month      state number_of_fire      Date
0     1998   January       Acre        0 Fires  1/1/1998
1     1999   January       Acre        0 Fires  1/1/1999
2     2000   January       Acre        0 Fires  1/1/2000
3     2001   January       Acre        0 Fires  1/1/2001
4     2002   January       Acre        0 Fires  1/1/2002
...    ...       ...        ...            ...       ...
6449  2012  December  Tocantins            128  1/1/2012
6450  2013  December  Tocantins             85  1/1/2013
6451  2014  December  Tocantins            223  1/1/2014
6452  2015  December  Tocantins            373  1/1/2015
6453  2016  December  Tocantins            119  1/1/2016

[6424 rows x 5 columns]

In [47]:
d3['month']=d3['month'].str.upper()
d3

      year     month      state number_of_fire      Date
0     1998   JANUARY       Acre        0 Fires  1/1/1998
1     1999   JANUARY       Acre        0 Fires  1/1/1999
2     2000   JANUARY       Acre        0 Fires  1/1/2000
3     2001   JANUARY       Acre        0 Fires  1/1/2001
4     2002   JANUARY       Acre        0 Fires  1/1/2002
...    ...       ...        ...            ...       ...
6449  2012  DECEMBER  Tocantins            128  1/1/2012
6450  2013  DECEMBER  Tocantins             85  1/1/2013
6451  2014  DECEMBER  Tocantins            223  1/1/2014
6452  2015  DECEMBER  Tocantins            373  1/1/2015
6453  2016  DECEMBER  Tocantins            119  1/1/2016

[6424 rows x 5 columns]

In [48]:
d3['state']=d3['state'].str.swapcase()
d3

      year     month      state number_of_fire      Date
0     1998   JANUARY       aCRE        0 Fires  1/1/1998
1     1999   JANUARY       aCRE        0 Fires  1/1/1999
2     2000   JANUARY       aCRE        0 Fires  1/1/2000
3     2001   JANUARY       aCRE        0 Fires  1/1/2001
4     2002   JANUARY       aCRE        0 Fires  1/1/2002
...    ...       ...        ...            ...       ...
6449  2012  DECEMBER  tOCANTINS            128  1/1/2012
6450  2013  DECEMBER  tOCANTINS             85  1/1/2013
6451  2014  DECEMBER  tOCANTINS            223  1/1/2014
6452  2015  DECEMBER  tOCANTINS            373  1/1/2015
6453  2016  DECEMBER  tOCANTINS            119  1/1/2016

[6424 rows x 5 columns]

In [49]:
d3['number_of_fire']=d3['number_of_fire'].str.strip(' Fires')
d3

      year     month      state number_of_fire      Date
0     1998   JANUARY       aCRE              0  1/1/1998
1     1999   JANUARY       aCRE              0  1/1/1999
2     2000   JANUARY       aCRE              0  1/1/2000
3     2001   JANUARY       aCRE              0  1/1/2001
4     2002   JANUARY       aCRE              0  1/1/2002
...    ...       ...        ...            ...       ...
6449  2012  DECEMBER  tOCANTINS            128  1/1/2012
6450  2013  DECEMBER  tOCANTINS             85  1/1/2013
6451  2014  DECEMBER  tOCANTINS            223  1/1/2014
6452  2015  DECEMBER  tOCANTINS            373  1/1/2015
6453  2016  DECEMBER  tOCANTINS            119  1/1/2016

[6424 rows x 5 columns]

In [50]:
# avg= d3['number_of_fire'].mean()     
# avg                                          # TypeError: can only concatenate str (not "int") to str



# here we got some data that include int float NaN or null so in next step we count for how many null vales are there

In [51]:
d3[d3['number_of_fire'].isnull()]                       # here we got 132 of null value

      year      month      state number_of_fire      Date
68    2006      APRIL       aCRE            NaN  1/1/2006
110   2008       JUNE       aCRE            NaN  1/1/2008
127   2005       JULY       aCRE            NaN  1/1/2005
206   2004   NOVEMBER       aCRE            NaN  1/1/2004
217   2015   NOVEMBER       aCRE            NaN  1/1/2015
...    ...        ...        ...            ...       ...
6305  2008        MAY  tOCANTINS            NaN  1/1/2008
6354  2017       JULY  tOCANTINS            NaN  1/1/2017
6383  2006  SEPTEMBER  tOCANTINS            NaN  1/1/2006
6415  1998   NOVEMBER  tOCANTINS            NaN  1/1/1998
6428  2011   NOVEMBER  tOCANTINS            NaN  1/1/2011

[132 rows x 5 columns]

In [52]:
# dropna() removes all rows that contain at least one NULL (NaN) value.

#d3.dropna(inplace=True)           # in next step we delete all null value which may loss data but now we are just doing next we will solve
#d3                                # we had 6454 data after removing duplicate we got 6424 data then after removing null value we got 6292

In [53]:
# then we change the data type from str to float then int

# d3['number_of_fire']=d3['number_of_fire'].astype(float)       # changed to float
# d3['number_of_fire']=d3['number_of_fire'].astype(int)         # changed to int (we dont need to change to int)

type(d3['number_of_fire'][0])                                # to see the type its int now

str

In [54]:
#mean=d3['number_of_fire'].mean()
mean =111     # np.float64(111.11872218690401)    # mean=110.6

In [55]:
d3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6424 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   year            6424 non-null   int64
 1   month           6424 non-null   object
 2   state           6424 non-null   object
 3   number_of_fire  6292 non-null   object
 4   Date            6424 non-null   object
dtypes: int64(1), object(4)
memory usage: 559.2+ KB

In [56]:
d3['number_of_fire']=d3['number_of_fire'].fillna(mean)
d3

# here we fill all nul value with mean value then we can find the mean value

      year     month      state number_of_fire      Date
0     1998   JANUARY       aCRE              0  1/1/1998
1     1999   JANUARY       aCRE              0  1/1/1999
2     2000   JANUARY       aCRE              0  1/1/2000
3     2001   JANUARY       aCRE              0  1/1/2001
4     2002   JANUARY       aCRE              0  1/1/2002
...    ...       ...        ...            ...       ...
6449  2012  DECEMBER  tOCANTINS            128  1/1/2012
6450  2013  DECEMBER  tOCANTINS             85  1/1/2013
6451  2014  DECEMBER  tOCANTINS            223  1/1/2014
6452  2015  DECEMBER  tOCANTINS            373  1/1/2015
6453  2016  DECEMBER  tOCANTINS            119  1/1/2016

[6424 rows x 5 columns]

In [57]:
"""
We have to approach we did first one by removing null assign with mean value (i.e 111) then got mean
Then second by using to_numeric so here we change the data from str to direct numeric then perform mean function

"""

d3['number_of_fire']=pd.to_numeric(d3['number_of_fire'])

In [58]:
mean1 = d3['number_of_fire'].mean()
mean1

np.float64(111.17402179327522)

In [59]:
d3

      year     month      state  number_of_fire      Date
0     1998   JANUARY       aCRE             0.0  1/1/1998
1     1999   JANUARY       aCRE             0.0  1/1/1999
2     2000   JANUARY       aCRE             0.0  1/1/2000
3     2001   JANUARY       aCRE             0.0  1/1/2001
4     2002   JANUARY       aCRE             0.0  1/1/2002
...    ...       ...        ...             ...       ...
6449  2012  DECEMBER  tOCANTINS           128.0  1/1/2012
6450  2013  DECEMBER  tOCANTINS            85.0  1/1/2013
6451  2014  DECEMBER  tOCANTINS           223.0  1/1/2014
6452  2015  DECEMBER  tOCANTINS           373.0  1/1/2015
6453  2016  DECEMBER  tOCANTINS           119.0  1/1/2016

[6424 rows x 5 columns]

In [60]:
d3['number_of_fire']=pd.to_numeric(d3['number_of_fire'])
d3

      year     month      state  number_of_fire      Date
0     1998   JANUARY       aCRE             0.0  1/1/1998
1     1999   JANUARY       aCRE             0.0  1/1/1999
2     2000   JANUARY       aCRE             0.0  1/1/2000
3     2001   JANUARY       aCRE             0.0  1/1/2001
4     2002   JANUARY       aCRE             0.0  1/1/2002
...    ...       ...        ...             ...       ...
6449  2012  DECEMBER  tOCANTINS           128.0  1/1/2012
6450  2013  DECEMBER  tOCANTINS            85.0  1/1/2013
6451  2014  DECEMBER  tOCANTINS           223.0  1/1/2014
6452  2015  DECEMBER  tOCANTINS           373.0  1/1/2015
6453  2016  DECEMBER  tOCANTINS           119.0  1/1/2016

[6424 rows x 5 columns]

In [61]:
mean=d3['number_of_fire'].mean()
mean

np.float64(111.17402179327522)

In [62]:
"""
to save in file :-
df.to_csv('filename.extention')

"""

# d3.to_csv('21-11-25_Data_cleanig.csv')

"\nto save in file :-\ndf.to_csv('filename.extention')\n\n"

In [63]:
"""
dropping column:-
syntax:- df.drop('col_name', axis=1) 


"""

"\ndropping column:-\nsyntax:- df.drop('col_name', axis=1) \n\n\n"

In [64]:
d3.drop('state', axis=1,inplace=True)    
d3

                                                         # we can use any one of it

# d3=d3.drop('state', axis=1)     
# d3

      year     month  number_of_fire      Date
0     1998   JANUARY             0.0  1/1/1998
1     1999   JANUARY             0.0  1/1/1999
2     2000   JANUARY             0.0  1/1/2000
3     2001   JANUARY             0.0  1/1/2001
4     2002   JANUARY             0.0  1/1/2002
...    ...       ...             ...       ...
6449  2012  DECEMBER           128.0  1/1/2012
6450  2013  DECEMBER            85.0  1/1/2013
6451  2014  DECEMBER           223.0  1/1/2014
6452  2015  DECEMBER           373.0  1/1/2015
6453  2016  DECEMBER           119.0  1/1/2016

[6424 rows x 4 columns]

In [65]:
# d3=d3.drop(['month','year'], axis=1)    # we comment because it will show error  its for drop more then one column at a time
# d3

In [66]:
"""
to drop row
syntax

"""

d3.drop(d3.index[[0,3,6,8,6000]],inplace=True)   # to drop row

d3

      year     month  number_of_fire      Date
1     1999   JANUARY             0.0  1/1/1999
2     2000   JANUARY             0.0  1/1/2000
4     2002   JANUARY             0.0  1/1/2002
5     2003   JANUARY            10.0  1/1/2003
7     2005   JANUARY            12.0  1/1/2005
...    ...       ...             ...       ...
6449  2012  DECEMBER           128.0  1/1/2012
6450  2013  DECEMBER            85.0  1/1/2013
6451  2014  DECEMBER           223.0  1/1/2014
6452  2015  DECEMBER           373.0  1/1/2015
6453  2016  DECEMBER           119.0  1/1/2016

[6419 rows x 4 columns]

In [67]:
# to reset index value 
# 

d3.reset_index(inplace=True)
d3

      index  year     month  number_of_fire      Date
0         1  1999   JANUARY             0.0  1/1/1999
1         2  2000   JANUARY             0.0  1/1/2000
2         4  2002   JANUARY             0.0  1/1/2002
3         5  2003   JANUARY            10.0  1/1/2003
4         7  2005   JANUARY            12.0  1/1/2005
...     ...   ...       ...             ...       ...
6414   6449  2012  DECEMBER           128.0  1/1/2012
6415   6450  2013  DECEMBER            85.0  1/1/2013
6416   6451  2014  DECEMBER           223.0  1/1/2014
6417   6452  2015  DECEMBER           373.0  1/1/2015
6418   6453  2016  DECEMBER           119.0  1/1/2016

[6419 rows x 5 columns]

In [68]:
d3.columns    # to know the column

Index(['index', 'year', 'month', 'number_of_fire', 'Date'], dtype='object')

In [69]:
# after reset we got an extra column named index now we will drop that column

d3.drop('index',axis=1,inplace=True)           # to drop a colmn

In [70]:
d3

      year     month  number_of_fire      Date
0     1999   JANUARY             0.0  1/1/1999
1     2000   JANUARY             0.0  1/1/2000
2     2002   JANUARY             0.0  1/1/2002
3     2003   JANUARY            10.0  1/1/2003
4     2005   JANUARY            12.0  1/1/2005
...    ...       ...             ...       ...
6414  2012  DECEMBER           128.0  1/1/2012
6415  2013  DECEMBER            85.0  1/1/2013
6416  2014  DECEMBER           223.0  1/1/2014
6417  2015  DECEMBER           373.0  1/1/2015
6418  2016  DECEMBER           119.0  1/1/2016

[6419 rows x 4 columns]

In [71]:
d3.head()

   year    month  number_of_fire      Date
0  1999  JANUARY             0.0  1/1/1999
1  2000  JANUARY             0.0  1/1/2000
2  2002  JANUARY             0.0  1/1/2002
3  2003  JANUARY            10.0  1/1/2003
4  2005  JANUARY            12.0  1/1/2005

In [72]:
# It reorders the columns of the DataFrame d3 by selecting them in a new order using column index positions.

d3=d3[d3.columns[[3,0,1,2]]]
d3

          Date  year     month  number_of_fire
0     1/1/1999  1999   JANUARY             0.0
1     1/1/2000  2000   JANUARY             0.0
2     1/1/2002  2002   JANUARY             0.0
3     1/1/2003  2003   JANUARY            10.0
4     1/1/2005  2005   JANUARY            12.0
...        ...   ...       ...             ...
6414  1/1/2012  2012  DECEMBER           128.0
6415  1/1/2013  2013  DECEMBER            85.0
6416  1/1/2014  2014  DECEMBER           223.0
6417  1/1/2015  2015  DECEMBER           373.0
6418  1/1/2016  2016  DECEMBER           119.0

[6419 rows x 4 columns]

In [73]:
import numpy as np


df6=pd.DataFrame({'name':['karan','rohan','mohan','sam'],   
                  'age':[19,20,np.nan,23]})
df6

    name   age
0  karan  19.0
1  rohan  20.0
2  mohan   NaN
3    sam  23.0

In [74]:
df6.fillna(method='ffill')

C:\Users\yamin\AppData\Local\Temp\ipykernel_18152\3829696483.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df6.fillna(method='ffill')

    name   age
0  karan  19.0
1  rohan  20.0
2  mohan  20.0
3    sam  23.0

In [75]:
df6.fillna(method='backfill')

C:\Users\yamin\AppData\Local\Temp\ipykernel_18152\3491395408.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df6.fillna(method='backfill')

    name   age
0  karan  19.0
1  rohan  20.0
2  mohan  23.0
3    sam  23.0

In [76]:
d4 = pd.read_csv("https://raw.githubusercontent.com/whoknowayush/DataAnalysis-Dataset/main/Datasets-Practice/winequalityN.csv")
d4

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,white,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,white,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,red,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
6493,red,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,NaN,11.2,6
6494,red,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
6495,red,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
6496,red,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [77]:
d4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   type                  6497 non-null   object
 1   fixed acidity         6487 non-null   float64
 2   volatile acidity      6489 non-null   float64
 3   citric acid           6494 non-null   float64
 4   residual sugar        6495 non-null   float64
 5   chlorides             6495 non-null   float64
 6   free sulfur dioxide   6497 non-null   float64
 7   total sulfur dioxide  6497 non-null   float64
 8   density               6497 non-null   float64
 9   pH                    6488 non-null   float64
 10  sulphates             6493 non-null   float64
 11  alcohol               6497 non-null   float64
 12  quality               6497 non-null   int64
dtypes: float64(11), int64(1), object(1)
memory usage: 660.0+ KB

In [78]:
null1=d4.isnull().sum().sum()      #Count total null values in entire dataset
print(null1)                       #38

null2=d4.isnull().sum()            # show how many null valuse are in each column
print(null2)

null3=d4.isnull().sum(axis=1)
print(null3)

38
type                     0
fixed acidity           10
volatile acidity         8
citric acid              3
residual sugar           2
chlorides                2
free sulfur dioxide      0
total sulfur dioxide     0
density                  0
pH                       9
sulphates                4
alcohol                  0
quality                  0
dtype: int64
0       0
1       0
2       0
3       0
4       0
       ..
6492    0
6493    1
6494    0
6495    0
6496    0
Length: 6497, dtype: int64

In [79]:
d4.dropna(inplace=True)
d4

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,white,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,white,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6491,red,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6
6492,red,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
6494,red,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
6495,red,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
6496,red,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [80]:
d4.reset_index(inplace=True)
d4

,index,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,0,white,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,1,white,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,2,white,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,3,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,4,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6458,6491,red,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6
6459,6492,red,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
6460,6494,red,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
6461,6495,red,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
6462,6496,red,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [81]:
d4.columns

Index(['index', 'type', 'fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality'],
      dtype='object')

In [82]:
d4.drop('index',axis=1,inplace=True)
d4

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,white,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,white,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6458,red,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6
6459,red,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
6460,red,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
6461,red,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
6462,red,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [83]:
#set_index() does not move a column to index 0. It turns the column into the index.

d4.set_index('alcohol',inplace=True)     
d4

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,quality
alcohol,,,,,,,,,,,,
8.8,white,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,6
9.5,white,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,6
10.1,white,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,6
9.9,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,6
9.9,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,6
...,...,...,...,...,...,...,...,...,...,...,...,...
9.5,red,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,6
10.5,red,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,5
11.0,red,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,6
10.2,red,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,5
11.0,red,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,6

In [84]:
d5 = pd.read_csv("https://raw.githubusercontent.com/whoknowayush/DataAnalysis-Dataset/main/Datasets-Practice/titanic.csv")
d5

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [85]:
# Extract Title

# d5['title'] = d5['name'].str.split(",").str[1].str.split(".").str[0].str.strip()         # Using str & split function  (Try to avoid it)
# d5  


d5['Title'] = [name.split(",")[1].split(".")[0].strip() for name in d5['name']]            # Using comprehention (use this its better)
d5

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived,Title
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1,Miss
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1,Master
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0,Miss
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0,Mr
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0,Mrs
...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0,Miss
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0,Miss
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0,Mr
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0,Mr
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0,Mr

In [86]:
# Extract First Name

# d5['First_Name'] = d5['name'].str.split(".", n=1).str[1].str.strip().str.split().str[0]      # Using str & split function(Try to avoid it)
# d5 

d5['First_Name'] = [name.split(".")[1].strip().split()[0] for name in d5['name']]          # Using comprehention (use this its better)
d5

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived,Title,First_Name
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1,Miss,Elisabeth
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1,Master,Hudson
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0,Miss,Helen
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0,Mr,Hudson
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0,Mrs,Hudson
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0,Miss,Hileni
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0,Miss,Thamine
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0,Mr,Mapriededer
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0,Mr,Ortin
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0,Mr,Leo

In [87]:
d6 = pd.read_csv("https://raw.githubusercontent.com/whoknowayush/DataAnalysis-Dataset/main/Datasets-Practice/titanic.csv")
d6

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [88]:
d6.groupby('pclass')

In [89]:
d6['pclass'].unique()

array([1, 2, 3])

In [90]:
d6['pclass'].value_counts()

pclass
3    709
1    323
2    277
Name: count, dtype: int64

In [91]:
d6[d6['pclass']==1]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
318,1,"Williams-Lambert, Mr. Fletcher Fellows",male,NaN,0,0,113510,35.0000,C128,S,0
319,1,"Wilson, Miss. Helen Alice",female,31.0000,0,0,16966,134.5000,E39 E41,C,1
320,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S,1
321,1,"Wright, Mr. George",male,62.0000,0,0,113807,26.5500,NaN,S,0
322,1,"Young, Miss. Marie Grice",female,36.0000,0,0,PC 17760,135.6333,C32,C,1

In [92]:
d6.groupby('pclass').get_group(1)

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
318,1,"Williams-Lambert, Mr. Fletcher Fellows",male,NaN,0,0,113510,35.0000,C128,S,0
319,1,"Wilson, Miss. Helen Alice",female,31.0000,0,0,16966,134.5000,E39 E41,C,1
320,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S,1
321,1,"Wright, Mr. George",male,62.0000,0,0,113807,26.5500,NaN,S,0
322,1,"Young, Miss. Marie Grice",female,36.0000,0,0,PC 17760,135.6333,C32,C,1

In [93]:
d6.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [94]:
# both are same gives same ans

# d6[(d6['sex']=='female') & (d6['survived']==1)]     

d6.groupby('sex').get_group('female').groupby('survived').get_group(1)

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0,0,0,24160,211.3375,B5,S,1
6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,1
8,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,1
11,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.0,1,0,PC 17757,227.5250,C62 C64,C,1
12,1,"Aubart, Mme. Leontine Pauline",female,24.0,0,0,PC 17477,69.3000,B35,C,1
...,...,...,...,...,...,...,...,...,...,...,...
1260,3,"Turja, Miss. Anna Sofia",female,18.0,0,0,4138,9.8417,NaN,S,1
1261,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S,1
1286,3,"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",female,38.0,0,0,2688,7.2292,NaN,C,1
1290,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,1
1300,3,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.0,1,0,2659,14.4542,NaN,C,1

In [95]:
# d6[(d6['age']>25) & (d6['sibsp']==2) & (d6['embarked']=='S')] 

d6.groupby('sibsp').get_group(2).groupby('embarked').get_group('S').groupby(d6['age'] > 25).get_group(True)

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
8,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,1
42,1,"Brown, Mrs. John Murray (Caroline Lane Lamson)",female,59.0,2,0,11769,51.4792,C101,S,1
79,1,"Cornell, Mrs. Robert Clifford (Malvina Helen L...",female,55.0,2,0,11770,25.7000,C101,S,1
119,1,"Frauenthal, Dr. Henry William",male,50.0,2,0,PC 17611,133.6500,NaN,S,1
443,2,"Hickman, Mr. Lewis",male,32.0,2,0,S.O.C. 14879,73.5000,NaN,S,0
837,3,"Gustafsson, Mr. Anders Vilhelm",male,37.0,2,0,3101276,7.9250,NaN,S,0
838,3,"Gustafsson, Mr. Johan Birger",male,28.0,2,0,3101277,7.9250,NaN,S,0
848,3,"Hansen, Mr. Claus Peter",male,41.0,2,0,350026,14.1083,NaN,S,0
933,3,"Kink, Mr. Vincenz",male,26.0,2,0,315151,8.6625,NaN,S,0

In [96]:
d7 = pd.read_csv("https://raw.githubusercontent.com/whoknowayush/DataAnalysis-Dataset/refs/heads/main/Datasets-Practice/hr_data.csv")
d7

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

In [97]:
d7.groupby('salary').get_group('high').groupby('department').get_group('sales').groupby('number_project').get_group(2)

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
774,5398,2,152,3,0,1,0,sales,high
1398,8921,2,156,3,0,1,0,sales,high
2763,16544,2,184,2,0,0,0,sales,high
3307,19826,2,148,3,0,0,0,sales,high
4131,24551,2,154,4,0,0,0,sales,high
4132,58727,2,201,2,0,0,0,sales,high
5197,30581,2,157,6,0,0,0,sales,high
5523,32519,2,106,2,0,0,1,sales,high
5662,33214,2,140,4,0,0,0,sales,high
7420,43918,2,204,3,0,0,0,sales,high
7492,70662,2,96,2,0,0,0,sales,high
7803,46108,2,115,3,0,0,0,sales,high
7957,27255,2,107,4,0,0,0,sales,high
8115,47948,2,188,2,0,0,0,sales,high
9858,58137,2,180,2,0,0,0,sales,high
11019,64655,2,285,3,0,0,0,sales,high
11196,36376,2,274,10,0,0,0,sales,high
11203,65691,2,162,3,1,0,0,sales,high
12774,76187,2,152,3,0,1,0,sales,high
13230,82572,2,285,3,0,0,0,sales,high
13407,78345,2,274,10,0,0,0,sales,high
13414,54996,2,162,3,1,0,0,sales,high

In [98]:
d7

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

In [99]:
print(d7.groupby('department').get_group('support').groupby('number_project').get_group(2)['time_spend_company'],'\n')
print(d7.groupby('department').get_group('support').groupby('number_project').get_group(2)['time_spend_company'].sum())

46       3
48       3
49       3
51       3
52       3
        ..
14992    3
14994    3
14995    3
14996    3
14998    3
Name: time_spend_company, Length: 350, dtype: int64

1110

In [100]:
print(d7.groupby('time_spend_company').get_group(3).groupby('salary').get_group('low')['average_montly_hours'],'\n')
print(d7.groupby('time_spend_company').get_group(3).groupby('salary').get_group('low')['average_montly_hours'].sum())

0        157
4        159
5        153
9        142
10       135
        ...
14992    155
14994    151
14995    160
14996    143
14998    158
Name: average_montly_hours, Length: 3205, dtype: int64

587109

In [101]:
from numpy._core.numeric import count_nonzero

d7.pivot_table(values=['average_montly_hours','number_project','time_spend_company'],index='salary',aggfunc=[count_nonzero,max,min])

C:\Users\yamin\AppData\Local\Temp\ipykernel_18152\881582215.py:3: FutureWarning: The provided callable <built-in function max> is currently using DataFrameGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  d7.pivot_table(values=['average_montly_hours','number_project','time_spend_company'],index='salary',aggfunc=[count_nonzero,max,min])
C:\Users\yamin\AppData\Local\Temp\ipykernel_18152\881582215.py:3: FutureWarning: The provided callable <built-in function min> is currently using DataFrameGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  d7.pivot_table(values=['average_montly_hours','number_project','time_spend_company'],index='salary',aggfunc=[count_nonzero,max,min])

              count_nonzero                                    \
       average_montly_hours number_project time_spend_company
salary
high                   1237           1237               1237
low                    7316           7316               7316
medium                 6446           6446               6446

                        max                                    \
       average_montly_hours number_project time_spend_company
salary
high                    307              7                 10
low                     310              7                 10
medium                  310              7                 10

                        min
       average_montly_hours number_project time_spend_company
salary
high                     96              2                  2
low                      96              2                  2
medium                   96              2                  2

In [102]:
from numpy._core.numeric import count_nonzero

d7.pivot_table(values=['average_montly_hours','number_project','time_spend_company'],index='department',aggfunc=[count_nonzero,max,min])

C:\Users\yamin\AppData\Local\Temp\ipykernel_18152\2902444740.py:3: FutureWarning: The provided callable <built-in function max> is currently using DataFrameGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  d7.pivot_table(values=['average_montly_hours','number_project','time_spend_company'],index='department',aggfunc=[count_nonzero,max,min])
C:\Users\yamin\AppData\Local\Temp\ipykernel_18152\2902444740.py:3: FutureWarning: The provided callable <built-in function min> is currently using DataFrameGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  d7.pivot_table(values=['average_montly_hours','number_project','time_spend_company'],index='department',aggfunc=[count_nonzero,max,min])

                   count_nonzero                                    \
            average_montly_hours number_project time_spend_company
department
IT                          1227           1227               1227
RandD                        787            787                787
accounting                   767            767                767
hr                           739            739                739
management                   630            630                630
marketing                    858            858                858
product_mng                  902            902                902
sales                       4140           4140               4140
support                     2229           2229               2229
technical                   2720           2720               2720

                             max                                    \
            average_montly_hours number_project time_spend_company
department
IT                           308              7                 10
RandD                        308              7                  8
accounting                   310              7                 10
hr                           310              7                  8
management                   307              7                 10
marketing                    310              7                 10
product_mng                  310              7                 10
sales                        310              7                 10
support                      310              7                 10
technical                    310              7                 10

                             min
            average_montly_hours number_project time_spend_company
department
IT                            96              2                  2
RandD                         98              2                  2
accounting                    97              2                  2
hr                            98              2                  2
management                    97              2                  2
marketing                     96              2                  2
product_mng                   98              2                  2
sales                         96              2                  2
support                       96              2                  2
technical                     97              2                  2

In [103]:
df1 = pd.DataFrame({
    'emp_name': ['Amit Sharma', 'Priya Singh', 'Rahul Das', 'Sneha Patil', 'Vikram Rao'],
    'emp_id': [101, 102, 103, 104, 105],
    'emp_sal': [45000, 52000, 48000, 61000, 55000],
    'emp_exp': [2, 3, 1, 5, 4],
    'emp_dept': ['HR', 'IT', 'Finance', 'Marketing', 'IT']
})

df1

      emp_name  emp_id  emp_sal  emp_exp   emp_dept
0  Amit Sharma     101    45000        2         HR
1  Priya Singh     102    52000        3         IT
2    Rahul Das     103    48000        1    Finance
3  Sneha Patil     104    61000        5  Marketing
4   Vikram Rao     105    55000        4         IT

In [104]:
df2 = pd.DataFrame({
    'cand_name': ['Rohit Verma', 'Anita Rao', 'Karan Mehta', 'Deepa Nair', 'Suresh Pillai'],
    'cand_phno': ['9876543210', '9123456780', '9988776655', '9090909090', '8001234567'],
    'cand_dept': ['IT', 'HR', 'Finance', 'Marketing', 'IT'],
    'cand_loc': ['Delhi', 'Mumbai', 'Bangalore', 'Hyderabad', 'Chennai']
})

df2

       cand_name   cand_phno  cand_dept   cand_loc
0    Rohit Verma  9876543210         IT      Delhi
1      Anita Rao  9123456780         HR     Mumbai
2    Karan Mehta  9988776655    Finance  Bangalore
3     Deepa Nair  9090909090  Marketing  Hyderabad
4  Suresh Pillai  8001234567         IT    Chennai

In [105]:
# its vertical merging
pd.concat([df1,df2])

,emp_name,emp_id,emp_sal,emp_exp,emp_dept,cand_name,cand_phno,cand_dept,cand_loc
0,Amit Sharma,101.0,45000.0,2.0,HR,NaN,NaN,NaN,NaN
1,Priya Singh,102.0,52000.0,3.0,IT,NaN,NaN,NaN,NaN
2,Rahul Das,103.0,48000.0,1.0,Finance,NaN,NaN,NaN,NaN
3,Sneha Patil,104.0,61000.0,5.0,Marketing,NaN,NaN,NaN,NaN
4,Vikram Rao,105.0,55000.0,4.0,IT,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,Rohit Verma,9876543210,IT,Delhi
1,NaN,NaN,NaN,NaN,NaN,Anita Rao,9123456780,HR,Mumbai
2,NaN,NaN,NaN,NaN,NaN,Karan Mehta,9988776655,Finance,Bangalore
3,NaN,NaN,NaN,NaN,NaN,Deepa Nair,9090909090,Marketing,Hyderabad
4,NaN,NaN,NaN,NaN,NaN,Suresh Pillai,8001234567,IT,Chennai

In [106]:
# its horizontal merging
pd.concat([df1,df2],axis=1)

,emp_name,emp_id,emp_sal,emp_exp,emp_dept,cand_name,cand_phno,cand_dept,cand_loc
0,Amit Sharma,101,45000,2,HR,Rohit Verma,9876543210,IT,Delhi
1,Priya Singh,102,52000,3,IT,Anita Rao,9123456780,HR,Mumbai
2,Rahul Das,103,48000,1,Finance,Karan Mehta,9988776655,Finance,Bangalore
3,Sneha Patil,104,61000,5,Marketing,Deepa Nair,9090909090,Marketing,Hyderabad
4,Vikram Rao,105,55000,4,IT,Suresh Pillai,8001234567,IT,Chennai

#### Revision

In [107]:
w=pd.read_csv('https://raw.githubusercontent.com/whoknowayush/DataAnalysis-Dataset/refs/heads/main/Datasets-Practice/winequalityN.csv')
w

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,white,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,white,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,red,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
6493,red,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,NaN,11.2,6
6494,red,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
6495,red,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
6496,red,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [108]:
print(w.shape,'\n')
print(w.info(),'\n')
print(w.describe())

(6497, 13)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   type                  6497 non-null   object
 1   fixed acidity         6487 non-null   float64
 2   volatile acidity      6489 non-null   float64
 3   citric acid           6494 non-null   float64
 4   residual sugar        6495 non-null   float64
 5   chlorides             6495 non-null   float64
 6   free sulfur dioxide   6497 non-null   float64
 7   total sulfur dioxide  6497 non-null   float64
 8   density               6497 non-null   float64
 9   pH                    6488 non-null   float64
 10  sulphates             6493 non-null   float64
 11  alcohol               6497 non-null   float64
 12  quality               6497 non-null   int64
dtypes: float64(11), int64(1), object(1)
memory usage: 660.0+ KB
None

       fixed acidity  volatile acidity  citric acid  residual sugar  \
count    6487.000000       6489.000000  6494.000000     6495.000000
mean        7.216579          0.339691     0.318722        5.444326
std         1.296750          0.164649     0.145265        4.758125
min         3.800000          0.080000     0.000000        0.600000
25%         6.400000          0.230000     0.250000        1.800000
50%         7.000000          0.290000     0.310000        3.000000
75%         7.700000          0.400000     0.390000        8.100000
max        15.900000          1.580000     1.660000       65.800000

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  6495.000000          6497.000000           6497.000000  6497.000000
mean      0.056042            30.525319            115.744574     0.994697
std       0.035036            17.749400             56.521855     0.002999
min       0.009000             1.000000              6.000000     0.987110
25%       0.038000            17.000000             77.000000     0.992340
50%       0.047000            29.000000            118.000000     0.994890
75%       0.065000            41.000000            156.000000     0.996990
max       0.611000           289.000000            440.000000     1.038980

                pH    sulphates      alcohol      quality
count  6488.000000  6493.000000  6497.000000  6497.000000
mean      3.218395     0.531215    10.491801     5.818378
std       0.160748     0.148814     1.192712     0.873255
min       2.720000     0.220000     8.000000     3.000000
25%       3.110000     0.430000     9.500000     5.000000
50%       3.210000     0.510000    10.300000     6.000000
75%       3.320000     0.600000    11.300000     6.000000
max       4.010000     2.000000    14.900000     9.000000

In [109]:
print(w.duplicated().sum())             # count duplicates
w = w.drop_duplicates()                 # remove duplicates
w

1168

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,white,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,white,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
6,white,6.2,0.320,0.16,7.0,0.045,30.0,136.0,0.99490,3.18,0.47,9.6,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6491,red,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6
6492,red,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
6493,red,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,NaN,11.2,6
6495,red,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
6496,red,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [110]:
null1=w.isnull().sum().sum()      #Count total null values in entire dataset
print(null1)                       #38

null2=w.isnull().sum()            # show how many null valuse are in each column
print(null2)

null3=w.isnull().sum(axis=1)      # How many null values are present in that particular row
print(null3)

38
type                     0
fixed acidity           10
volatile acidity         8
citric acid              3
residual sugar           2
chlorides                2
free sulfur dioxide      0
total sulfur dioxide     0
density                  0
pH                       9
sulphates                4
alcohol                  0
quality                  0
dtype: int64
0       0
1       0
2       0
3       0
6       0
       ..
6491    0
6492    0
6493    1
6495    0
6496    0
Length: 5329, dtype: int64

In [111]:
w.dropna(inplace=True)           # to drop null values
w

C:\Users\yamin\AppData\Local\Temp\ipykernel_18152\1625064457.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  w.dropna(inplace=True)           # to drop null values

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,white,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,white,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
6,white,6.2,0.320,0.16,7.0,0.045,30.0,136.0,0.99490,3.18,0.47,9.6,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6490,red,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
6491,red,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6
6492,red,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
6495,red,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
6496,red,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [112]:
w.reset_index(inplace=True)
w

,index,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,0,white,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,1,white,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,2,white,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,3,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,6,white,6.2,0.320,0.16,7.0,0.045,30.0,136.0,0.99490,3.18,0.47,9.6,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5290,6490,red,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
5291,6491,red,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6
5292,6492,red,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
5293,6495,red,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
5294,6496,red,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [113]:
w.columns

Index(['index', 'type', 'fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality'],
      dtype='object')

In [114]:
w.drop('index',axis=1,inplace=True)
w

C:\Users\yamin\AppData\Local\Temp\ipykernel_18152\349681415.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  w.drop('index',axis=1,inplace=True)

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,white,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,white,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,white,6.2,0.320,0.16,7.0,0.045,30.0,136.0,0.99490,3.18,0.47,9.6,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5290,red,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
5291,red,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6
5292,red,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
5293,red,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
5294,red,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [115]:
w.columns = w.columns.str.lower().str.strip().str.replace(' ', '_')
w

,type,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol,quality
0,white,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,white,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,white,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,white,6.2,0.320,0.16,7.0,0.045,30.0,136.0,0.99490,3.18,0.47,9.6,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5290,red,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
5291,red,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6
5292,red,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
5293,red,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
5294,red,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [116]:
w.dtypes

type                     object
fixed_acidity           float64
volatile_acidity        float64
citric_acid             float64
residual_sugar          float64
chlorides               float64
free_sulfur_dioxide     float64
total_sulfur_dioxide    float64
density                 float64
ph                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

In [117]:
w['quality'] = w['quality'].astype(int)
w.dtypes

C:\Users\yamin\AppData\Local\Temp\ipykernel_18152\3589011925.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  w['quality'] = w['quality'].astype(int)

type                     object
fixed_acidity           float64
volatile_acidity        float64
citric_acid             float64
residual_sugar          float64
chlorides               float64
free_sulfur_dioxide     float64
total_sulfur_dioxide    float64
density                 float64
ph                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

In [118]:
w

,type,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol,quality
0,white,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,white,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,white,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,white,6.2,0.320,0.16,7.0,0.045,30.0,136.0,0.99490,3.18,0.47,9.6,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5290,red,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
5291,red,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6
5292,red,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
5293,red,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
5294,red,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [119]:
e=pd.read_csv('https://raw.githubusercontent.com/whoknowayush/DataAnalysis-Dataset/refs/heads/main/Datasets-Practice/employee_data.csv')
e

,emp_id,full_name,age,gender,department,salary,join_date,exp_years,emp_status
0,101,John A. Smith,28.0,male,Sales,45000.0,2017-08-19,5.0,permanent
1,102,Sarah-Louise James,NaN,female,Marketing,50000.0,2018-11-03,NaN,permanent
2,110,Rajesh Kumar,45.0,male,Sales,90000.0,2010-02-23,14.0,permanent
3,103,Mark O'Donnell,35.0,male,HR,52000.0,2016-03-11,8.0,NaN
4,104,Emily Jackson-Smith,29.0,female,R&D,65000.0,NaN,6.0,contract
5,102,Sarah-Louise James,NaN,female,Marketing,50000.0,2018-11-03,NaN,permanent
6,110,Rajesh Kumar,45.0,male,Sales,90000.0,2010-02-23,14.0,permanent
7,105,Samuel L. Jackson,42.0,Male,IT,NaN,2015-07-01,12.0,permanent
8,106,Priya Ghosh,31.0,NaN,Marketing,58000.0,2019-01-10,4.0,contract
9,102,Sarah-Louise James,NaN,female,Marketing,50000.0,2018-11-03,NaN,permanent
10,110,Rajesh Kumar,45.0,male,Sales,90000.0,2010-02-23,14.0,permanent
11,107,Susan M. Thompson,39.0,Female,IT,75000.0,2014-09-21,NaN,permanent
12,108,Brian P. McDonald,33.0,Male,HR,48000.0,2017-04-15,6.0,permanent
13,109,Sophia Y. Richardson,26.0,Female,IT,55000.0,2020-05-30,3.0,contract
14,110,Rajesh Kumar,45.0,male,Sales,90000.0,2010-02-23,14.0,permanent
15,102,Sarah-Louise James,NaN,female,Marketing,50000.0,2018-11-03,NaN,permanent

In [120]:
print(e.shape,'\n')
print(e.info())

(16, 9)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   emp_id      16 non-null     int64
 1   full_name   16 non-null     object
 2   age         12 non-null     float64
 3   gender      15 non-null     object
 4   department  16 non-null     object
 5   salary      15 non-null     float64
 6   join_date   15 non-null     object
 7   exp_years   11 non-null     float64
 8   emp_status  15 non-null     object
dtypes: float64(3), int64(1), object(5)
memory usage: 1.3+ KB
None

In [121]:
# to fill the age col by takimg mean of age

mean=e['age'].mean()
e['age']=e['age'].fillna(mean).astype(int)
e

,emp_id,full_name,age,gender,department,salary,join_date,exp_years,emp_status
0,101,John A. Smith,28,male,Sales,45000.0,2017-08-19,5.0,permanent
1,102,Sarah-Louise James,36,female,Marketing,50000.0,2018-11-03,NaN,permanent
2,110,Rajesh Kumar,45,male,Sales,90000.0,2010-02-23,14.0,permanent
3,103,Mark O'Donnell,35,male,HR,52000.0,2016-03-11,8.0,NaN
4,104,Emily Jackson-Smith,29,female,R&D,65000.0,NaN,6.0,contract
5,102,Sarah-Louise James,36,female,Marketing,50000.0,2018-11-03,NaN,permanent
6,110,Rajesh Kumar,45,male,Sales,90000.0,2010-02-23,14.0,permanent
7,105,Samuel L. Jackson,42,Male,IT,NaN,2015-07-01,12.0,permanent
8,106,Priya Ghosh,31,NaN,Marketing,58000.0,2019-01-10,4.0,contract
9,102,Sarah-Louise James,36,female,Marketing,50000.0,2018-11-03,NaN,permanent
10,110,Rajesh Kumar,45,male,Sales,90000.0,2010-02-23,14.0,permanent
11,107,Susan M. Thompson,39,Female,IT,75000.0,2014-09-21,NaN,permanent
12,108,Brian P. McDonald,33,Male,HR,48000.0,2017-04-15,6.0,permanent
13,109,Sophia Y. Richardson,26,Female,IT,55000.0,2020-05-30,3.0,contract
14,110,Rajesh Kumar,45,male,Sales,90000.0,2010-02-23,14.0,permanent
15,102,Sarah-Louise James,36,female,Marketing,50000.0,2018-11-03,NaN,permanent

In [122]:
# to assing gender for row no 8 ita possible in small data we cant assume some ones gender or cant take mean

e.loc[8,'gender']='Female'
e

,emp_id,full_name,age,gender,department,salary,join_date,exp_years,emp_status
0,101,John A. Smith,28,male,Sales,45000.0,2017-08-19,5.0,permanent
1,102,Sarah-Louise James,36,female,Marketing,50000.0,2018-11-03,NaN,permanent
2,110,Rajesh Kumar,45,male,Sales,90000.0,2010-02-23,14.0,permanent
3,103,Mark O'Donnell,35,male,HR,52000.0,2016-03-11,8.0,NaN
4,104,Emily Jackson-Smith,29,female,R&D,65000.0,NaN,6.0,contract
5,102,Sarah-Louise James,36,female,Marketing,50000.0,2018-11-03,NaN,permanent
6,110,Rajesh Kumar,45,male,Sales,90000.0,2010-02-23,14.0,permanent
7,105,Samuel L. Jackson,42,Male,IT,NaN,2015-07-01,12.0,permanent
8,106,Priya Ghosh,31,Female,Marketing,58000.0,2019-01-10,4.0,contract
9,102,Sarah-Louise James,36,female,Marketing,50000.0,2018-11-03,NaN,permanent
10,110,Rajesh Kumar,45,male,Sales,90000.0,2010-02-23,14.0,permanent
11,107,Susan M. Thompson,39,Female,IT,75000.0,2014-09-21,NaN,permanent
12,108,Brian P. McDonald,33,Male,HR,48000.0,2017-04-15,6.0,permanent
13,109,Sophia Y. Richardson,26,Female,IT,55000.0,2020-05-30,3.0,contract
14,110,Rajesh Kumar,45,male,Sales,90000.0,2010-02-23,14.0,permanent
15,102,Sarah-Louise James,36,female,Marketing,50000.0,2018-11-03,NaN,permanent

In [123]:
e['gender']=e['gender'].str.capitalize()
e

,emp_id,full_name,age,gender,department,salary,join_date,exp_years,emp_status
0,101,John A. Smith,28,Male,Sales,45000.0,2017-08-19,5.0,permanent
1,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,NaN,permanent
2,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14.0,permanent
3,103,Mark O'Donnell,35,Male,HR,52000.0,2016-03-11,8.0,NaN
4,104,Emily Jackson-Smith,29,Female,R&D,65000.0,NaN,6.0,contract
5,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,NaN,permanent
6,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14.0,permanent
7,105,Samuel L. Jackson,42,Male,IT,NaN,2015-07-01,12.0,permanent
8,106,Priya Ghosh,31,Female,Marketing,58000.0,2019-01-10,4.0,contract
9,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,NaN,permanent
10,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14.0,permanent
11,107,Susan M. Thompson,39,Female,IT,75000.0,2014-09-21,NaN,permanent
12,108,Brian P. McDonald,33,Male,HR,48000.0,2017-04-15,6.0,permanent
13,109,Sophia Y. Richardson,26,Female,IT,55000.0,2020-05-30,3.0,contract
14,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14.0,permanent
15,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,NaN,permanent

In [124]:
# Samuel L. Jackson have no sal to fill it we take avg sal of I.T dept

mean_IT_sal=e.groupby('department').get_group('IT')['salary'].mean()
e['salary']=e['salary'].fillna(mean_IT_sal)
e

,emp_id,full_name,age,gender,department,salary,join_date,exp_years,emp_status
0,101,John A. Smith,28,Male,Sales,45000.0,2017-08-19,5.0,permanent
1,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,NaN,permanent
2,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14.0,permanent
3,103,Mark O'Donnell,35,Male,HR,52000.0,2016-03-11,8.0,NaN
4,104,Emily Jackson-Smith,29,Female,R&D,65000.0,NaN,6.0,contract
5,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,NaN,permanent
6,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14.0,permanent
7,105,Samuel L. Jackson,42,Male,IT,65000.0,2015-07-01,12.0,permanent
8,106,Priya Ghosh,31,Female,Marketing,58000.0,2019-01-10,4.0,contract
9,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,NaN,permanent
10,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14.0,permanent
11,107,Susan M. Thompson,39,Female,IT,75000.0,2014-09-21,NaN,permanent
12,108,Brian P. McDonald,33,Male,HR,48000.0,2017-04-15,6.0,permanent
13,109,Sophia Y. Richardson,26,Female,IT,55000.0,2020-05-30,3.0,contract
14,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14.0,permanent
15,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,NaN,permanent

In [125]:
e['join_date']=e['join_date'].fillna("")

mean_exp=e['exp_years'].mean()

e['exp_years']=e['exp_years'].fillna(mean_exp).astype(int)

e['emp_status']=e['emp_status'].fillna(method='backfill')
e

C:\Users\yamin\AppData\Local\Temp\ipykernel_18152\1001078983.py:7: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  e['emp_status']=e['emp_status'].fillna(method='backfill')

,emp_id,full_name,age,gender,department,salary,join_date,exp_years,emp_status
0,101,John A. Smith,28,Male,Sales,45000.0,2017-08-19,5,permanent
1,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent
2,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent
3,103,Mark O'Donnell,35,Male,HR,52000.0,2016-03-11,8,contract
4,104,Emily Jackson-Smith,29,Female,R&D,65000.0,,6,contract
5,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent
6,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent
7,105,Samuel L. Jackson,42,Male,IT,65000.0,2015-07-01,12,permanent
8,106,Priya Ghosh,31,Female,Marketing,58000.0,2019-01-10,4,contract
9,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent
10,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent
11,107,Susan M. Thompson,39,Female,IT,75000.0,2014-09-21,9,permanent
12,108,Brian P. McDonald,33,Male,HR,48000.0,2017-04-15,6,permanent
13,109,Sophia Y. Richardson,26,Female,IT,55000.0,2020-05-30,3,contract
14,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent
15,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent

In [126]:
# Rename columns to Upper Case
e.columns = e.columns.str.upper()
e

,EMP_ID,FULL_NAME,AGE,GENDER,DEPARTMENT,SALARY,JOIN_DATE,EXP_YEARS,EMP_STATUS
0,101,John A. Smith,28,Male,Sales,45000.0,2017-08-19,5,permanent
1,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent
2,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent
3,103,Mark O'Donnell,35,Male,HR,52000.0,2016-03-11,8,contract
4,104,Emily Jackson-Smith,29,Female,R&D,65000.0,,6,contract
5,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent
6,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent
7,105,Samuel L. Jackson,42,Male,IT,65000.0,2015-07-01,12,permanent
8,106,Priya Ghosh,31,Female,Marketing,58000.0,2019-01-10,4,contract
9,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent
10,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent
11,107,Susan M. Thompson,39,Female,IT,75000.0,2014-09-21,9,permanent
12,108,Brian P. McDonald,33,Male,HR,48000.0,2017-04-15,6,permanent
13,109,Sophia Y. Richardson,26,Female,IT,55000.0,2020-05-30,3,contract
14,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent
15,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent

In [127]:
# Filter active employees with experience ≥ 5 years and salary > 50k
active_employees=e[(e['EXP_YEARS']>=5) & (e['SALARY']>50000)]
active_employees

,EMP_ID,FULL_NAME,AGE,GENDER,DEPARTMENT,SALARY,JOIN_DATE,EXP_YEARS,EMP_STATUS
2,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent
3,103,Mark O'Donnell,35,Male,HR,52000.0,2016-03-11,8,contract
4,104,Emily Jackson-Smith,29,Female,R&D,65000.0,,6,contract
6,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent
7,105,Samuel L. Jackson,42,Male,IT,65000.0,2015-07-01,12,permanent
10,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent
11,107,Susan M. Thompson,39,Female,IT,75000.0,2014-09-21,9,permanent
14,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent

In [128]:
#  Get employees who joined after 2018 and are in ‘hr’ or ‘finance’

e['JOIN_DATE'] = pd.to_datetime(e['JOIN_DATE'])  # ensure datetime format

e[(e['JOIN_DATE']>='2019-01-01') & (e['DEPARTMENT']== 'HR') | (e['DEPARTMENT']=='Sales') ]

,EMP_ID,FULL_NAME,AGE,GENDER,DEPARTMENT,SALARY,JOIN_DATE,EXP_YEARS,EMP_STATUS
0,101,John A. Smith,28,Male,Sales,45000.0,2017-08-19,5,permanent
2,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent
6,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent
10,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent
14,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent

In [129]:
# 1. years_with_company
e['YEARS_WITH_COMPANY'] = 2025 - e['JOIN_DATE'].dt.year
e

,EMP_ID,FULL_NAME,AGE,GENDER,DEPARTMENT,SALARY,JOIN_DATE,EXP_YEARS,EMP_STATUS,YEARS_WITH_COMPANY
0,101,John A. Smith,28,Male,Sales,45000.0,2017-08-19,5,permanent,8.0
1,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0
2,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0
3,103,Mark O'Donnell,35,Male,HR,52000.0,2016-03-11,8,contract,9.0
4,104,Emily Jackson-Smith,29,Female,R&D,65000.0,NaT,6,contract,NaN
5,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0
6,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0
7,105,Samuel L. Jackson,42,Male,IT,65000.0,2015-07-01,12,permanent,10.0
8,106,Priya Ghosh,31,Female,Marketing,58000.0,2019-01-10,4,contract,6.0
9,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0
10,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0
11,107,Susan M. Thompson,39,Female,IT,75000.0,2014-09-21,9,permanent,11.0
12,108,Brian P. McDonald,33,Male,HR,48000.0,2017-04-15,6,permanent,8.0
13,109,Sophia Y. Richardson,26,Female,IT,55000.0,2020-05-30,3,contract,5.0
14,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0
15,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0

In [130]:
# 2. is_senior flag (>=10 years experience)
e['IS_SENIOR'] = e['EXP_YEARS'] >= 10
e

,EMP_ID,FULL_NAME,AGE,GENDER,DEPARTMENT,SALARY,JOIN_DATE,EXP_YEARS,EMP_STATUS,YEARS_WITH_COMPANY,IS_SENIOR
0,101,John A. Smith,28,Male,Sales,45000.0,2017-08-19,5,permanent,8.0,False
1,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0,False
2,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0,True
3,103,Mark O'Donnell,35,Male,HR,52000.0,2016-03-11,8,contract,9.0,False
4,104,Emily Jackson-Smith,29,Female,R&D,65000.0,NaT,6,contract,NaN,False
5,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0,False
6,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0,True
7,105,Samuel L. Jackson,42,Male,IT,65000.0,2015-07-01,12,permanent,10.0,True
8,106,Priya Ghosh,31,Female,Marketing,58000.0,2019-01-10,4,contract,6.0,False
9,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0,False
10,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0,True
11,107,Susan M. Thompson,39,Female,IT,75000.0,2014-09-21,9,permanent,11.0,False
12,108,Brian P. McDonald,33,Male,HR,48000.0,2017-04-15,6,permanent,8.0,False
13,109,Sophia Y. Richardson,26,Female,IT,55000.0,2020-05-30,3,contract,5.0,False
14,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0,True
15,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0,False

In [131]:
# 3. Extract first_name and last_name
e['FIRST_NAME'] = e['FULL_NAME'].str.split().str[0]
e['LAST_NAME'] = e['FULL_NAME'].str.split().str[-1]
e

,EMP_ID,FULL_NAME,AGE,GENDER,DEPARTMENT,SALARY,JOIN_DATE,EXP_YEARS,EMP_STATUS,YEARS_WITH_COMPANY,IS_SENIOR,FIRST_NAME,LAST_NAME
0,101,John A. Smith,28,Male,Sales,45000.0,2017-08-19,5,permanent,8.0,False,John,Smith
1,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0,False,Sarah-Louise,James
2,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0,True,Rajesh,Kumar
3,103,Mark O'Donnell,35,Male,HR,52000.0,2016-03-11,8,contract,9.0,False,Mark,O'Donnell
4,104,Emily Jackson-Smith,29,Female,R&D,65000.0,NaT,6,contract,NaN,False,Emily,Jackson-Smith
5,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0,False,Sarah-Louise,James
6,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0,True,Rajesh,Kumar
7,105,Samuel L. Jackson,42,Male,IT,65000.0,2015-07-01,12,permanent,10.0,True,Samuel,Jackson
8,106,Priya Ghosh,31,Female,Marketing,58000.0,2019-01-10,4,contract,6.0,False,Priya,Ghosh
9,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0,False,Sarah-Louise,James
10,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0,True,Rajesh,Kumar
11,107,Susan M. Thompson,39,Female,IT,75000.0,2014-09-21,9,permanent,11.0,False,Susan,Thompson
12,108,Brian P. McDonald,33,Male,HR,48000.0,2017-04-15,6,permanent,8.0,False,Brian,McDonald
13,109,Sophia Y. Richardson,26,Female,IT,55000.0,2020-05-30,3,contract,5.0,False,Sophia,Richardson
14,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0,True,Rajesh,Kumar
15,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0,False,Sarah-Louise,James

In [132]:
# 4. Experience-to-age ratio
e['EXP_AGE_RATIO'] = e['EXP_YEARS'] / e['AGE']
e

,EMP_ID,FULL_NAME,AGE,GENDER,DEPARTMENT,SALARY,JOIN_DATE,EXP_YEARS,EMP_STATUS,YEARS_WITH_COMPANY,IS_SENIOR,FIRST_NAME,LAST_NAME,EXP_AGE_RATIO
0,101,John A. Smith,28,Male,Sales,45000.0,2017-08-19,5,permanent,8.0,False,John,Smith,0.178571
1,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0,False,Sarah-Louise,James,0.250000
2,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0,True,Rajesh,Kumar,0.311111
3,103,Mark O'Donnell,35,Male,HR,52000.0,2016-03-11,8,contract,9.0,False,Mark,O'Donnell,0.228571
4,104,Emily Jackson-Smith,29,Female,R&D,65000.0,NaT,6,contract,NaN,False,Emily,Jackson-Smith,0.206897
5,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0,False,Sarah-Louise,James,0.250000
6,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0,True,Rajesh,Kumar,0.311111
7,105,Samuel L. Jackson,42,Male,IT,65000.0,2015-07-01,12,permanent,10.0,True,Samuel,Jackson,0.285714
8,106,Priya Ghosh,31,Female,Marketing,58000.0,2019-01-10,4,contract,6.0,False,Priya,Ghosh,0.129032
9,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0,False,Sarah-Louise,James,0.250000
10,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0,True,Rajesh,Kumar,0.311111
11,107,Susan M. Thompson,39,Female,IT,75000.0,2014-09-21,9,permanent,11.0,False,Susan,Thompson,0.230769
12,108,Brian P. McDonald,33,Male,HR,48000.0,2017-04-15,6,permanent,8.0,False,Brian,McDonald,0.181818
13,109,Sophia Y. Richardson,26,Female,IT,55000.0,2020-05-30,3,contract,5.0,False,Sophia,Richardson,0.115385
14,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0,True,Rajesh,Kumar,0.311111
15,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0,False,Sarah-Louise,James,0.250000

In [133]:
# 5. Name length
e['NAME_LENGTH'] = e['FULL_NAME'].str.len()
e

,EMP_ID,FULL_NAME,AGE,GENDER,DEPARTMENT,SALARY,JOIN_DATE,EXP_YEARS,EMP_STATUS,YEARS_WITH_COMPANY,IS_SENIOR,FIRST_NAME,LAST_NAME,EXP_AGE_RATIO,NAME_LENGTH
0,101,John A. Smith,28,Male,Sales,45000.0,2017-08-19,5,permanent,8.0,False,John,Smith,0.178571,13
1,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0,False,Sarah-Louise,James,0.250000,18
2,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0,True,Rajesh,Kumar,0.311111,12
3,103,Mark O'Donnell,35,Male,HR,52000.0,2016-03-11,8,contract,9.0,False,Mark,O'Donnell,0.228571,14
4,104,Emily Jackson-Smith,29,Female,R&D,65000.0,NaT,6,contract,NaN,False,Emily,Jackson-Smith,0.206897,19
5,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0,False,Sarah-Louise,James,0.250000,18
6,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0,True,Rajesh,Kumar,0.311111,12
7,105,Samuel L. Jackson,42,Male,IT,65000.0,2015-07-01,12,permanent,10.0,True,Samuel,Jackson,0.285714,17
8,106,Priya Ghosh,31,Female,Marketing,58000.0,2019-01-10,4,contract,6.0,False,Priya,Ghosh,0.129032,11
9,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0,False,Sarah-Louise,James,0.250000,18
10,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0,True,Rajesh,Kumar,0.311111,12
11,107,Susan M. Thompson,39,Female,IT,75000.0,2014-09-21,9,permanent,11.0,False,Susan,Thompson,0.230769,17
12,108,Brian P. McDonald,33,Male,HR,48000.0,2017-04-15,6,permanent,8.0,False,Brian,McDonald,0.181818,17
13,109,Sophia Y. Richardson,26,Female,IT,55000.0,2020-05-30,3,contract,5.0,False,Sophia,Richardson,0.115385,20
14,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0,True,Rajesh,Kumar,0.311111,12
15,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0,False,Sarah-Louise,James,0.250000,18

In [134]:
# 6. Combined feature: dept_seniority
e['DEPT_SENIORITY'] = e['DEPARTMENT'] + '_' + e['IS_SENIOR'].astype(str)
e

,EMP_ID,FULL_NAME,AGE,GENDER,DEPARTMENT,SALARY,JOIN_DATE,EXP_YEARS,EMP_STATUS,YEARS_WITH_COMPANY,IS_SENIOR,FIRST_NAME,LAST_NAME,EXP_AGE_RATIO,NAME_LENGTH,DEPT_SENIORITY
0,101,John A. Smith,28,Male,Sales,45000.0,2017-08-19,5,permanent,8.0,False,John,Smith,0.178571,13,Sales_False
1,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0,False,Sarah-Louise,James,0.250000,18,Marketing_False
2,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0,True,Rajesh,Kumar,0.311111,12,Sales_True
3,103,Mark O'Donnell,35,Male,HR,52000.0,2016-03-11,8,contract,9.0,False,Mark,O'Donnell,0.228571,14,HR_False
4,104,Emily Jackson-Smith,29,Female,R&D,65000.0,NaT,6,contract,NaN,False,Emily,Jackson-Smith,0.206897,19,R&D_False
5,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0,False,Sarah-Louise,James,0.250000,18,Marketing_False
6,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0,True,Rajesh,Kumar,0.311111,12,Sales_True
7,105,Samuel L. Jackson,42,Male,IT,65000.0,2015-07-01,12,permanent,10.0,True,Samuel,Jackson,0.285714,17,IT_True
8,106,Priya Ghosh,31,Female,Marketing,58000.0,2019-01-10,4,contract,6.0,False,Priya,Ghosh,0.129032,11,Marketing_False
9,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0,False,Sarah-Louise,James,0.250000,18,Marketing_False
10,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0,True,Rajesh,Kumar,0.311111,12,Sales_True
11,107,Susan M. Thompson,39,Female,IT,75000.0,2014-09-21,9,permanent,11.0,False,Susan,Thompson,0.230769,17,IT_False
12,108,Brian P. McDonald,33,Male,HR,48000.0,2017-04-15,6,permanent,8.0,False,Brian,McDonald,0.181818,17,HR_False
13,109,Sophia Y. Richardson,26,Female,IT,55000.0,2020-05-30,3,contract,5.0,False,Sophia,Richardson,0.115385,20,IT_False
14,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0,True,Rajesh,Kumar,0.311111,12,Sales_True
15,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0,False,Sarah-Louise,James,0.250000,18,Marketing_False

In [135]:
# 7. salary_relative = salary / dept_avg_salary
dept_avg_salary = e.groupby('DEPARTMENT')['SALARY'].transform('mean')
e['SALARY_RELATIVE'] = e['SALARY'] / dept_avg_salary
e

,EMP_ID,FULL_NAME,AGE,GENDER,DEPARTMENT,SALARY,JOIN_DATE,EXP_YEARS,EMP_STATUS,YEARS_WITH_COMPANY,IS_SENIOR,FIRST_NAME,LAST_NAME,EXP_AGE_RATIO,NAME_LENGTH,DEPT_SENIORITY,SALARY_RELATIVE
0,101,John A. Smith,28,Male,Sales,45000.0,2017-08-19,5,permanent,8.0,False,John,Smith,0.178571,13,Sales_False,0.555556
1,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0,False,Sarah-Louise,James,0.250000,18,Marketing_False,0.968992
2,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0,True,Rajesh,Kumar,0.311111,12,Sales_True,1.111111
3,103,Mark O'Donnell,35,Male,HR,52000.0,2016-03-11,8,contract,9.0,False,Mark,O'Donnell,0.228571,14,HR_False,1.040000
4,104,Emily Jackson-Smith,29,Female,R&D,65000.0,NaT,6,contract,NaN,False,Emily,Jackson-Smith,0.206897,19,R&D_False,1.000000
5,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0,False,Sarah-Louise,James,0.250000,18,Marketing_False,0.968992
6,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0,True,Rajesh,Kumar,0.311111,12,Sales_True,1.111111
7,105,Samuel L. Jackson,42,Male,IT,65000.0,2015-07-01,12,permanent,10.0,True,Samuel,Jackson,0.285714,17,IT_True,1.000000
8,106,Priya Ghosh,31,Female,Marketing,58000.0,2019-01-10,4,contract,6.0,False,Priya,Ghosh,0.129032,11,Marketing_False,1.124031
9,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0,False,Sarah-Louise,James,0.250000,18,Marketing_False,0.968992
10,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0,True,Rajesh,Kumar,0.311111,12,Sales_True,1.111111
11,107,Susan M. Thompson,39,Female,IT,75000.0,2014-09-21,9,permanent,11.0,False,Susan,Thompson,0.230769,17,IT_False,1.153846
12,108,Brian P. McDonald,33,Male,HR,48000.0,2017-04-15,6,permanent,8.0,False,Brian,McDonald,0.181818,17,HR_False,0.960000
13,109,Sophia Y. Richardson,26,Female,IT,55000.0,2020-05-30,3,contract,5.0,False,Sophia,Richardson,0.115385,20,IT_False,0.846154
14,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0,True,Rajesh,Kumar,0.311111,12,Sales_True,1.111111
15,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0,False,Sarah-Louise,James,0.250000,18,Marketing_False,0.968992

In [136]:
# Set EMP_ID as Index

e.set_index('EMP_ID', inplace=True)
e

,FULL_NAME,AGE,GENDER,DEPARTMENT,SALARY,JOIN_DATE,EXP_YEARS,EMP_STATUS,YEARS_WITH_COMPANY,IS_SENIOR,FIRST_NAME,LAST_NAME,EXP_AGE_RATIO,NAME_LENGTH,DEPT_SENIORITY,SALARY_RELATIVE
EMP_ID,,,,,,,,,,,,,,,,
101,John A. Smith,28,Male,Sales,45000.0,2017-08-19,5,permanent,8.0,False,John,Smith,0.178571,13,Sales_False,0.555556
102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0,False,Sarah-Louise,James,0.250000,18,Marketing_False,0.968992
110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0,True,Rajesh,Kumar,0.311111,12,Sales_True,1.111111
103,Mark O'Donnell,35,Male,HR,52000.0,2016-03-11,8,contract,9.0,False,Mark,O'Donnell,0.228571,14,HR_False,1.040000
104,Emily Jackson-Smith,29,Female,R&D,65000.0,NaT,6,contract,NaN,False,Emily,Jackson-Smith,0.206897,19,R&D_False,1.000000
102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0,False,Sarah-Louise,James,0.250000,18,Marketing_False,0.968992
110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0,True,Rajesh,Kumar,0.311111,12,Sales_True,1.111111
105,Samuel L. Jackson,42,Male,IT,65000.0,2015-07-01,12,permanent,10.0,True,Samuel,Jackson,0.285714,17,IT_True,1.000000
106,Priya Ghosh,31,Female,Marketing,58000.0,2019-01-10,4,contract,6.0,False,Priya,Ghosh,0.129032,11,Marketing_False,1.124031
102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0,False,Sarah-Louise,James,0.250000,18,Marketing_False,0.968992
110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0,True,Rajesh,Kumar,0.311111,12,Sales_True,1.111111
107,Susan M. Thompson,39,Female,IT,75000.0,2014-09-21,9,permanent,11.0,False,Susan,Thompson,0.230769,17,IT_False,1.153846
108,Brian P. McDonald,33,Male,HR,48000.0,2017-04-15,6,permanent,8.0,False,Brian,McDonald,0.181818,17,HR_False,0.960000
109,Sophia Y. Richardson,26,Female,IT,55000.0,2020-05-30,3,contract,5.0,False,Sophia,Richardson,0.115385,20,IT_False,0.846154
110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0,True,Rajesh,Kumar,0.311111,12,Sales_True,1.111111
102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0,False,Sarah-Louise,James,0.250000,18,Marketing_False,0.968992

In [137]:
# Reset Index Back to Default

e.reset_index(inplace=True)
e.head()

,EMP_ID,FULL_NAME,AGE,GENDER,DEPARTMENT,SALARY,JOIN_DATE,EXP_YEARS,EMP_STATUS,YEARS_WITH_COMPANY,IS_SENIOR,FIRST_NAME,LAST_NAME,EXP_AGE_RATIO,NAME_LENGTH,DEPT_SENIORITY,SALARY_RELATIVE
0,101,John A. Smith,28,Male,Sales,45000.0,2017-08-19,5,permanent,8.0,False,John,Smith,0.178571,13,Sales_False,0.555556
1,102,Sarah-Louise James,36,Female,Marketing,50000.0,2018-11-03,9,permanent,7.0,False,Sarah-Louise,James,0.250000,18,Marketing_False,0.968992
2,110,Rajesh Kumar,45,Male,Sales,90000.0,2010-02-23,14,permanent,15.0,True,Rajesh,Kumar,0.311111,12,Sales_True,1.111111
3,103,Mark O'Donnell,35,Male,HR,52000.0,2016-03-11,8,contract,9.0,False,Mark,O'Donnell,0.228571,14,HR_False,1.040000
4,104,Emily Jackson-Smith,29,Female,R&D,65000.0,NaT,6,contract,NaN,False,Emily,Jackson-Smith,0.206897,19,R&D_False,1.000000

In [138]:
e.columns

Index(['EMP_ID', 'FULL_NAME', 'AGE', 'GENDER', 'DEPARTMENT', 'SALARY',
       'JOIN_DATE', 'EXP_YEARS', 'EMP_STATUS', 'YEARS_WITH_COMPANY',
       'IS_SENIOR', 'FIRST_NAME', 'LAST_NAME', 'EXP_AGE_RATIO', 'NAME_LENGTH',
       'DEPT_SENIORITY', 'SALARY_RELATIVE'],
      dtype='object')

In [139]:
# Move SALARY Column to the Front
cols = list(e.columns)
cols.insert(0, cols.pop(cols.index('SALARY')))
e = e[cols]
e

,SALARY,EMP_ID,FULL_NAME,AGE,GENDER,DEPARTMENT,JOIN_DATE,EXP_YEARS,EMP_STATUS,YEARS_WITH_COMPANY,IS_SENIOR,FIRST_NAME,LAST_NAME,EXP_AGE_RATIO,NAME_LENGTH,DEPT_SENIORITY,SALARY_RELATIVE
0,45000.0,101,John A. Smith,28,Male,Sales,2017-08-19,5,permanent,8.0,False,John,Smith,0.178571,13,Sales_False,0.555556
1,50000.0,102,Sarah-Louise James,36,Female,Marketing,2018-11-03,9,permanent,7.0,False,Sarah-Louise,James,0.250000,18,Marketing_False,0.968992
2,90000.0,110,Rajesh Kumar,45,Male,Sales,2010-02-23,14,permanent,15.0,True,Rajesh,Kumar,0.311111,12,Sales_True,1.111111
3,52000.0,103,Mark O'Donnell,35,Male,HR,2016-03-11,8,contract,9.0,False,Mark,O'Donnell,0.228571,14,HR_False,1.040000
4,65000.0,104,Emily Jackson-Smith,29,Female,R&D,NaT,6,contract,NaN,False,Emily,Jackson-Smith,0.206897,19,R&D_False,1.000000
5,50000.0,102,Sarah-Louise James,36,Female,Marketing,2018-11-03,9,permanent,7.0,False,Sarah-Louise,James,0.250000,18,Marketing_False,0.968992
6,90000.0,110,Rajesh Kumar,45,Male,Sales,2010-02-23,14,permanent,15.0,True,Rajesh,Kumar,0.311111,12,Sales_True,1.111111
7,65000.0,105,Samuel L. Jackson,42,Male,IT,2015-07-01,12,permanent,10.0,True,Samuel,Jackson,0.285714,17,IT_True,1.000000
8,58000.0,106,Priya Ghosh,31,Female,Marketing,2019-01-10,4,contract,6.0,False,Priya,Ghosh,0.129032,11,Marketing_False,1.124031
9,50000.0,102,Sarah-Louise James,36,Female,Marketing,2018-11-03,9,permanent,7.0,False,Sarah-Louise,James,0.250000,18,Marketing_False,0.968992
10,90000.0,110,Rajesh Kumar,45,Male,Sales,2010-02-23,14,permanent,15.0,True,Rajesh,Kumar,0.311111,12,Sales_True,1.111111
11,75000.0,107,Susan M. Thompson,39,Female,IT,2014-09-21,9,permanent,11.0,False,Susan,Thompson,0.230769,17,IT_False,1.153846
12,48000.0,108,Brian P. McDonald,33,Male,HR,2017-04-15,6,permanent,8.0,False,Brian,McDonald,0.181818,17,HR_False,0.960000
13,55000.0,109,Sophia Y. Richardson,26,Female,IT,2020-05-30,3,contract,5.0,False,Sophia,Richardson,0.115385,20,IT_False,0.846154
14,90000.0,110,Rajesh Kumar,45,Male,Sales,2010-02-23,14,permanent,15.0,True,Rajesh,Kumar,0.311111,12,Sales_True,1.111111
15,50000.0,102,Sarah-Louise James,36,Female,Marketing,2018-11-03,9,permanent,7.0,False,Sarah-Louise,James,0.250000,18,Marketing_False,0.968992

In [140]:
e=e[e.columns[[5]]]     #other method
e

   DEPARTMENT
0       Sales
1   Marketing
2       Sales
3          HR
4         R&D
5   Marketing
6       Sales
7          IT
8   Marketing
9   Marketing
10      Sales
11         IT
12         HR
13         IT
14      Sales
15  Marketing

In [141]:
# new_order = [
#     'SALARY', 'EMP_ID', 'FULL_NAME', 'FIRST_NAME', 'LAST_NAME', 'AGE', 'GENDER', 'DEPARTMENT', 'JOIN_DATE', 'EXP_YEARS', 'EMP_STATUS','YEARS_WITH_COMPANY',
#     'IS_SENIOR', 'EXP_AGE_RATIO', 'NAME_LENGTH','DEPT_SENIORITY', 'SALARY_RELATIVE']

# e = e[new_order]
# e

In [142]:
e.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   DEPARTMENT  16 non-null     object
dtypes: object(1)
memory usage: 260.0+ bytes